import openpyxl
import smtplib
import time
import os
import json
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication


# ============================================================
# 🔧 CONFIGURATION - EDIT THESE
# ============================================================

# Path to the xlsx file generated by the scraper
EXCEL_FILE = r"linkedin_posts_output/2026-06-15/linkedin_posts_2026-06-15_11-23-02.xlsx"

# Your Gmail credentials
SENDER_EMAIL = "parikhdhruv05@gmail.com"
SENDER_PASSWORD = "your-app-password-here"  # 16-char Gmail App Password (NOT your normal password)

# Optional: path to your resume PDF. Leave as "" if you don't want to attach.
RESUME_PATH = r""  # e.g. r"C:\Users\Admin\Documents\Dhruv_Parikh_Resume.pdf"

# Email subject & body (you can use {position} placeholder)
EMAIL_SUBJECT = "Application for {position} - Python Django Developer (2 Years Exp)"

EMAIL_BODY = """Hello,

I came across your job post for {position} on LinkedIn and would like to apply.

I'm a Python/Django Developer with 2 years of experience at Hexagon Infosoft,
Ahmedabad. My core stack includes Python, Django, Django REST Framework,
MySQL, REST APIs, YOLOv8, OpenCV, and web scraping (Selenium, BeautifulSoup).

I have attached my resume for your reference. Looking forward to hearing
from you.

Best regards,
Dhruv Parikh
{sender_email}
"""

# Delay between emails (seconds) - keep this reasonably high to avoid Gmail blocking you
DELAY_BETWEEN_EMAILS = 15

# File to keep track of emails already sent (so re-running doesn't duplicate)
SENT_LOG_FILE = "sent_emails_log.json"


# ============================================================
# LOAD ALREADY SENT EMAILS (to avoid duplicates on re-run)
# ============================================================

def load_sent_log():
    if os.path.exists(SENT_LOG_FILE):
        with open(SENT_LOG_FILE, "r", encoding="utf-8") as f:
            return set(json.load(f))
    return set()


def save_sent_log(sent_set):
    with open(SENT_LOG_FILE, "w", encoding="utf-8") as f:
        json.dump(list(sent_set), f, ensure_ascii=False, indent=2)


# ============================================================
# READ EMAILS + POSITION FROM EXCEL
# ============================================================

def get_email_position_pairs(excel_file):
    wb = openpyxl.load_workbook(excel_file)
    ws = wb.active

    # Find column indexes from header row
    headers = [cell.value for cell in ws[1]]
    email_col = headers.index("Email") + 1
    position_col = headers.index("Position") + 1

    pairs = []
    for row in ws.iter_rows(min_row=2, values_only=False):
        email_cell = row[email_col - 1].value
        position_cell = row[position_col - 1].value

        if not email_cell:
            continue

        # Email column can have multiple emails separated by ", "
        emails = [e.strip() for e in str(email_cell).split(",") if e.strip()]
        position = (position_cell or "this role").split("|")[0].strip()

        for email in emails:
            pairs.append((email, position))

    return pairs


# ============================================================
# SEND SINGLE EMAIL
# ============================================================

def send_email(smtp_server, to_email, position):
    msg = MIMEMultipart()
    msg["From"] = SENDER_EMAIL
    msg["To"] = to_email
    msg["Subject"] = EMAIL_SUBJECT.format(position=position)

    body = EMAIL_BODY.format(position=position, sender_email=SENDER_EMAIL)
    msg.attach(MIMEText(body, "plain"))

    # Attach resume if path is set
    if RESUME_PATH and os.path.exists(RESUME_PATH):
        with open(RESUME_PATH, "rb") as f:
            attachment = MIMEApplication(f.read(), _subtype="pdf")
            attachment.add_header(
                "Content-Disposition", "attachment",
                filename=os.path.basename(RESUME_PATH)
            )
            msg.attach(attachment)

    smtp_server.send_message(msg)


# ============================================================
# MAIN SCRIPT
# ============================================================

def main():
    if not os.path.exists(EXCEL_FILE):
        print(f"❌ Excel file not found: {EXCEL_FILE}")
        return

    pairs = get_email_position_pairs(EXCEL_FILE)

    # Remove duplicate emails (keep first position found for that email)
    seen = set()
    unique_pairs = []
    for email, position in pairs:
        if email.lower() not in seen:
            seen.add(email.lower())
            unique_pairs.append((email, position))

    print(f"📧 Found {len(unique_pairs)} unique email(s) in: {EXCEL_FILE}")

    sent_log = load_sent_log()
    to_send = [(e, p) for e, p in unique_pairs if e.lower() not in sent_log]

    print(f"➡️  {len(to_send)} email(s) pending (already sent: {len(unique_pairs) - len(to_send)})")

    if not to_send:
        print("✅ Nothing to send. All emails already sent earlier.")
        return

    # Connect to Gmail SMTP
    print("🔌 Connecting to Gmail SMTP...")
    smtp_server = smtplib.SMTP("smtp.gmail.com", 587)
    smtp_server.starttls()
    smtp_server.login(SENDER_EMAIL, SENDER_PASSWORD)
    print("✅ Logged in successfully\n")

    for i, (email, position) in enumerate(to_send, 1):
        try:
            print(f"[{i}/{len(to_send)}] 📤 Sending to {email}  (Position: {position}) ...")
            send_email(smtp_server, email, position)
            sent_log.add(email.lower())
            save_sent_log(sent_log)  # save after every send so progress isn't lost
            print(f"   ✅ Sent successfully")
        except Exception as e:
            print(f"   ❌ Failed to send to {email}: {e}")

        if i < len(to_send):
            print(f"   ⏳ Waiting {DELAY_BETWEEN_EMAILS} seconds...\n")
            time.sleep(DELAY_BETWEEN_EMAILS)

    smtp_server.quit()
    print("\n🎉 Done! All pending emails processed.")


if __name__ == "__main__":
    main()